services:
  app:
    image: sherman330turbo/docker-project-74:prod
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - npm-cache:/.npm
    environment:
      npm_config_cache: /.npm

volumes:
  npm-cache: