services:
  app:
    image: sherman330turbo/docker-project-74:prod
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["make", "test"]
    volumes:
      - npm-cache:/.npm
    environment:
      npm_config_cache: /.npm
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    shm_size: 128mb
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  npm-cache:
